export function generateE2EConfirmationComment(body) {
  return `🧪 **E2E Test Confirmation**\n\nHere is the script generated by Washmen AI for your confirmation before running the E2E test:\n\n\u003c!-- E2E_SCRIPT_START --\u003e\n${body}\n\u003c!-- E2E_SCRIPT_END --\u003e\n\nIf you confirm, reply with \"run e2e\" and Washmen AI will execute the script.\n\n---\n\n*This script is easily extractable between the markers for automation.*\n`;
}
