export function generateE2EConfirmationComment(body) {
  return `🧪 **E2E Test Confirmation**\n\nHere is the script generated by Washmen AI for your confirmation before running the E2E test:\n\n${body}\n\nIf you confirm, reply with \"run e2e\" and Washmen AI will execute the script.\n\n---`;
}
