name: Comment Reply Processor

on:
  repository_dispatch:
    types: [reply_and_react]

jobs:
  process-reply:
    runs-on: ubuntu-latest
    if: github.event.client_payload.pr_number
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Add Reaction to Comment
        uses: actions/github-script@v7
        with:
          script: |
            const reaction = '${{ github.event.client_payload.reaction }}';
            console.log(`Adding reaction: ${reaction} to comment ${{ github.event.client_payload.comment_id }}`);
            
            await github.rest.reactions.createForPullRequestReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ github.event.client_payload.comment_id }},
              content: reaction
            });
            
            console.log('Reaction added successfully');